import React from 'react';
import "./VerifyLogin.css";
import phone from "../assets/iPhone.png";

function VerifyLogin() {
    return (
        <>
            <section>
                <p> Sign in to <span>FinanceEdge</span> </p>
                <div>
                    <h2>2 step verification</h2>
                    <p>Enter the verification code generated by your phone ending in +xxx xxxxxxxx45.</p>

                    <div>
                        <div><img src={phone} alt="phone pic"/></div>
                        <div>
                            <p>Enter 2-step verification code</p>
                            <div>
                                <input type="password" placeholder="0 0 0 0 0 0"/>
                            
                                <button type="submit" className="bttn">Login</button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default VerifyLogin;
